### ISSUE TITLE
Error when trying to embed links into a spoiler

### ISSUE THREAD

**Issue by hartmannaf** [Fazendaaa/I-m-a-Spoiler-Bot#13]
When I try to share a spoiler containing an url, like "@ispoilerbot https://google.com" I get an error message, and I'm unable to share it. I tried different clients, URLs and accounts, so its probably a problem on the bots or its dependencies side.

**Comment by Fazendaaa** [comment]
Thanks for the heads up, @hartmannaf... I already saw it this, it is my "tiny-shortener" package -- I did an update to it that broke the bot --; but I'm already on it, just arrived at home and I will fix it soon.

**Comment by Fazendaaa** [comment]
@hartmannaf, just fixed :)

**Comment by hartmannaf** [comment]
It works, thx :)
