### ISSUE TITLE
Unable to click or copy links in spoilers

### ISSUE THREAD

**Issue by elessarkrin** [Fazendaaa/I-m-a-Spoiler-Bot#27]
Hi, I looks like the links can be click or copy when viewing the spoiler

![Screenshot_20200621-151909_Telegram](https://user-images.githubusercontent.com/14187067/85235522-c7835b00-b3d2-11ea-91a1-12f04e42402f.jpg)

**Comment by Fazendaaa** [comment]
Hello, @elessarkrin . Unfortunately this has more to do with the Telegram smartphone client, if you open this spoiler on the desktop client, you will be able to click on the link.
